version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      # - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      # - cd lib
      # - zip -r9 ../deployment_package.zip .
      - cd codeDeployDemo2
      - pip install -r requirements.txt -t lib
      - cd lib
      - zip -r9 ../codeDeployDemo2.zip .
      - cd ..
      - zip -g codeDeployDemo2.zip lambda_function.py
      # - cd ..
      # - cd .bjn
      
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name codeDeployDemo --zip-file fileb://codeDeployDemo2.zip
      # - aws lambda update-function-code --function-name codeDeployDemo2 --zip-file fileb://codeDeployDemo2.zip
      - echo "DONE!!"